function baseline_gui(action, option);
% call by Geomatics.m

if nargin < 1;
    action = 'initialize';
end;
if nargin < 2;
    option = 'none';
end;

global in1 in2 inputs

cfrm = [0 0.8 0.8];
con  = [1 1 1];
coff = [0.8 0.8 0.8];

string{1,:} = ('已選擇觀測資料，請輸入計算所需參數 ');
string{2,:} = ('程式執行中 ');
string{3,:} = ('解算完成。');
% string{1,:} = ('Load observation for evaluating... ');
% string{2,:} = ('Computing complete...Thanks for use ') ;     

switch action;
    case 'initialize'
        oldFigNumber = watchon;

        % 切換根目錄
        pth = which('baseline_gui');
        ui = findstr('\',pth);
        cd(pth(1:ui(end)-1));
        % --------------------------------
        % --- 產生一個全螢幕的圖形視窗 ---
        % --------------------------------
        figNumber = figure ('Name',' GNSS 基線計算程式 Version 2.0 ', ...
                            'Menubar','none', ...
                            'Position',[10 40 1008 696], ...
                            'Color',[0.9 0.9 0.8], ...
                            'NumberTitle','off', ...
                            'Visible','on');
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.005 0.003 0.5 0.03], ...
                       'String',' Copyright 2007 NCKU Department of Geomatics GNSS Group ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',[0.9 0.9 0.8], ...
                       'Foregroundcolor',[0 0 0]);
%% 參數設定選單
        % ----------------------------
        % --- 參數設定選單外框設定 ---
        % ----------------------------
        h = uipanel ('Units','normalized',...
                     'BorderType','etchedin',...
                     'FontSize',10,...
                     'title',' 觀測資料設定 ', ...
                     'Position',[0.02 0.46 0.50 0.51],...
                     'BackgroundColor',cfrm);
                 
        % --------------------
        % --- 檔案輸入選單 ---
        % --------------------
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.035 0.895 0.09 0.035], ...
                       'String','測站一 ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.895 0.25 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',con, ...
                       'Tag','InputFile1', ...
                       'Callback',['baseline_gui filename stn1']);
        h = uicontrol ('Style','Pushbutton', ...
                       'Units','normalized', ...
                       'Position',[0.375 0.895 0.05 0.035], ...
                       'String','Select', ...
                       'Tag','sO1',...
                       'Callback',['baseline_gui SelectFile In1']);
                   
%% Coordinate
        h = uipanel ('Units','normalized',...
                     'BorderType','line',...
                     'FontSize',10,...
                     'title',' 測站坐標 ', ...
                     'Position',[0.035 0.735 0.23 0.15],...
                     'BackgroundColor',cfrm);
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.045 0.82 0.08 0.035], ...
                       'String',' X (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.825 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Tag','wgsx1');
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.045 0.78 0.08 0.035], ...
                       'String',' Y (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.785 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con,...
                       'Tag','wgsy1');
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.045 0.74 0.08 0.035], ...
                       'String',' Z (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);    
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.745 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con,...
                       'Tag','wgsz1');
%% Antenna
        h = uipanel ('Units','normalized',...
                     'BorderType','line',...
                     'FontSize',10,...
                     'title',' 天線盤 ', ...
                     'Position',[0.275 0.735 0.23 0.15],...
                     'BackgroundColor',cfrm);
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.285 0.82 0.08 0.035], ...
                       'String',' H (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.365 0.825 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'String','', ...
                       'Tag','anth1');
%         h = uicontrol ('Style','Text', ...
%                        'Units','normalized', ...
%                        'Position',[0.285 0.78 0.08 0.035], ...
%                        'String',' E (m) ', ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','left', ...
%                        'BackgroundColor',cfrm);
%         h = uicontrol ('Style','Edit', ...
%                        'Units','normalized', ...
%                        'Position',[0.365 0.785 0.12 0.035], ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','center', ...
%                        'BackgroundColor',con,...
%                        'Tag','ante1');
%         h = uicontrol ('Style','Text', ...
%                        'Units','normalized', ...
%                        'Position',[0.285 0.74 0.08 0.035], ...
%                        'String',' N (m) ', ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','left', ...
%                        'BackgroundColor',cfrm);    
%         h = uicontrol ('Style','Edit', ...
%                        'Units','normalized', ...
%                        'Position',[0.365 0.745 0.12 0.035], ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','center', ...
%                        'BackgroundColor',con,...
%                        'Tag','antn1');


        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.035 0.685 0.09 0.035], ...
                       'String','測站二 ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.685 0.25 0.035], ...
                       'FontSize',10,...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',con, ...
                       'Enable','off', ...
                       'Tag','InputFile2', ...
                       'Callback',['baseline_gui filename stn2']);
        h = uicontrol ('Style','Pushbutton', ...
                       'Units','normalized', ...
                       'Position',[0.375 0.685 0.05 0.035], ...
                       'String','Select', ...
                       'Enable','off',...
                       'Tag','sO2',...
                       'Callback',['baseline_gui SelectFile In2']);
                   
%% Coordinate
        h = uipanel ('Units','normalized',...
                     'BorderType','line',...
                     'FontSize',10,...
                     'title',' 測站坐標 ', ...
                     'Position',[0.035 0.525 0.23 0.15],...
                     'BackgroundColor',cfrm);
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.045 0.61 0.08 0.035], ...
                       'String',' X (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.615 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con,...
                       'Enable','off',...
                       'Tag','wgsx2');
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.045 0.57 0.08 0.035], ...
                       'String',' Y (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.575 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Enable','off',...
                       'Tag','wgsy2');
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.045 0.53 0.08 0.035], ...
                       'String',' Z (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.535 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Enable','off',...
                       'Tag','wgsz2');
%% Antenna
        h = uipanel ('Units','normalized',...
                     'BorderType','line',...
                     'FontSize',10,...
                     'title',' 天線盤 ', ...
                     'Position',[0.275 0.525 0.23 0.15],...
                     'BackgroundColor',cfrm);
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.285 0.61 0.08 0.035], ...
                       'String',' H (m) ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.365 0.615 0.12 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con,...
                       'String','', ...
                       'Enable','off',...
                       'Tag','anth2');
%         h = uicontrol ('Style','Text', ...
%                        'Units','normalized', ...
%                        'Position',[0.285 0.57 0.08 0.035], ...
%                        'String',' E (m) ', ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','left', ...
%                        'BackgroundColor',cfrm);
%         h = uicontrol ('Style','Edit', ...
%                        'Units','normalized', ...
%                        'Position',[0.365 0.575 0.12 0.035], ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','center', ...
%                        'BackgroundColor',con, ...
%                        'Enable','off',...
%                        'Tag','ante2');
%         h = uicontrol ('Style','Text', ...
%                        'Units','normalized', ...
%                        'Position',[0.285 0.53 0.08 0.035], ...
%                        'String',' N (m) ', ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','left', ...
%                        'BackgroundColor',cfrm);
%         h = uicontrol ('Style','Edit', ...
%                        'Units','normalized', ...
%                        'Position',[0.365 0.535 0.12 0.035], ...
%                        'FontSize',10, ...
%                        'HorizontalAlignment','center', ...
%                        'BackgroundColor',con, ...
%                        'Enable','off',...
%                        'Tag','antn2');
%% Ephemeris
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.035 0.475 0.09 0.035], ...
                       'String','星曆檔 ', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.125 0.475 0.25 0.035], ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'Enable','off',...
                       'BackgroundColor',con, ...
                       'Tag','InputFile3', ...
                       'Callback',['baseline_gui filename eph']);
        h = uicontrol ('Style','Pushbutton', ...
                       'Units','normalized', ...
                       'Position',[0.375 0.475 0.05 0.035], ...
                       'String','Select', ...
                       'Enable','off',...
                       'Tag','sN',...
                       'Callback',['baseline_gui SelectFile In3']);

%% 觀測量選單
        % --------------------------
        % --- 觀測量選單外框設定 ---
        % --------------------------
        h = uipanel ('Units','normalized',...
                     'BorderType','etchedin',...
                     'FontSize',10,...
                     'title',' 觀測量選擇 ', ...
                     'Position',[0.53 0.46 0.151 0.51],...
                     'BackgroundColor',cfrm);
                       
        % ------------------
        % --- 觀測量選單 ---
        % ------------------
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'FontWeight','normal', ...
                       'Position',[0.54 0.895 0.06 0.035], ...
                       'String',' 載波相位', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',cfrm);
                   
%% GPS phase
        h = uipanel ('Units','normalized',...
                     'BorderType','line', ...
                     'FontSize',10, ...
                     'title',' GPS ', ...
                     'Position',[0.55 0.70 0.11 0.2],...
                     'BackgroundColor',cfrm);
        %% L1
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.552 0.82 0.06 0.035], ...
                       'String','L1', ...
                       'FontSize',10, ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','checkbox', ...
                       'Units','normalized', ...
                       'Position',[0.61 0.825 0.03 0.035], ...
                       'BackgroundColor',cfrm, ...
                       'Tag','pL1', ...
                       'Enable','Off', ...
                       'Value',0);
        %% L2
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.552 0.77 0.06 0.035], ...
                       'String','L2', ...
                       'FontSize',10, ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','checkbox', ...
                       'Units','normalized', ...
                       'Position',[0.61 0.775 0.03 0.035], ...
                       'BackgroundColor',cfrm, ...
                       'Tag','pL2', ...
                       'Enable','Off', ...
                       'Value',0);
        %% L5
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.552 0.72 0.06 0.035], ...
                       'String','L5', ...
                       'FontSize',10, ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','checkbox', ...
                       'Units','normalized', ...
                       'Position',[0.61 0.725 0.03 0.035], ...
                       'BackgroundColor',cfrm, ...
                       'Tag','pL5', ...
                       'Enable','Off', ...
                       'Value',0);
%% Galileo phase
        h = uipanel ('Units','normalized',...
                     'BorderType','line', ...
                     'FontSize',10, ...
                     'title',' Galileo ', ...
                     'Position',[0.55 0.48 0.11 0.2],...
                     'BackgroundColor',cfrm);

        %% E2-L1-E1
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.552 0.60 0.06 0.035], ...
                       'String','E1', ...
                       'FontSize',10, ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','checkbox', ...
                       'Units','normalized', ...
                       'Position',[0.61 0.605 0.03 0.035], ...
                       'BackgroundColor',cfrm, ...
                       'Tag','pE1', ...
                       'Enable','Off', ...
                       'Value',0);
        %% E5a
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.552 0.55 0.06 0.035], ...
                       'String','E5a', ...
                       'FontSize',10, ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','checkbox', ...
                       'Units','normalized', ...
                       'Position',[0.61 0.555 0.03 0.035], ...
                       'BackgroundColor',cfrm, ...
                       'Tag','pE5a', ...
                       'Enable','Off', ...
                       'Value',0);
        %% E5b
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.552 0.50 0.06 0.035], ...
                       'String','E5b', ...
                       'FontSize',10, ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','checkbox', ...
                       'Units','normalized', ...
                       'Position',[0.61 0.505 0.03 0.035], ...
                       'BackgroundColor',cfrm, ...
                       'Tag','pE5b', ...
                       'Enable','Off', ...
                       'Value',0);

%% 計算參數設定
        % ----------------------------
        % --- 計算參數選單外框設定 ---
        % ----------------------------  
        h = uipanel ('Units','normalized',...
                     'BorderType','etchedin',...
                     'FontSize',10,...
                     'title',' 計算參數設定 ', ...
                     'Position',[0.69 0.05 0.29 0.92],...
                     'BackgroundColor',cfrm);

        % ------------------
        % --- 計算參數設定 ---
        % ------------------
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'FontWeight','normal', ...
                       'Position',[0.705 0.895 0.12 0.035], ...
                       'String','Edit multiplier', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.85 0.895 0.11 0.035], ...
                       'FontSize',10, ...
                       'String','3.0', ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Tag','multi');                   
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'FontWeight','normal', ...
                       'Position',[0.705 0.855 0.12 0.035], ...
                       'String','Ratio cutoff', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.85 0.855 0.11 0.035], ...
                       'FontSize',10, ...
                       'String','3', ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Tag','ratiocut');
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'FontWeight','normal', ...
                       'Position',[0.705 0.815 0.12 0.035], ...
                       'String','連續時間間隔 (min)', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.85 0.815 0.11 0.035], ...
                       'FontSize',10, ...
                       'String','15', ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Tag','coninterval'); 
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'FontWeight','normal', ...
                       'Position',[0.705 0.775 0.12 0.035], ...
                       'String','衛星遮仰角 (deg)', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.85 0.775 0.11 0.035], ...
                       'FontSize',10, ...
                       'String','10', ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Tag','mask'); 
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'FontWeight','normal', ...
                       'Position',[0.705 0.735 0.15 0.035], ...
                       'String','週波脫落偵測門檻值 (m)', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.85 0.735 0.11 0.035], ...
                       'FontSize',10, ...
                       'String','2.5', ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Tag','cscutoff');                
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'FontWeight','normal', ...
                       'Position',[0.705 0.695 0.12 0.035], ...
                       'String','成果輸出', ...
                       'FontSize',10, ...
                       'HorizontalAlignment','left', ...
                       'BackgroundColor',cfrm);
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.85 0.695 0.11 0.035], ...
                       'FontSize',10, ...
                       'String','result.txt', ...
                       'HorizontalAlignment','center', ...
                       'BackgroundColor',con, ...
                       'Tag','resultout');
%% button
        h = uicontrol ('Style','Push', ...
                       'Units','normalized', ...
                       'Position',[0.705 0.2 0.12 0.06], ...
                       'String','基線計算', ...
                       'FontSize',10, ...
                       'Backgroundcolor',[0.925 0.914 0.847], ...
                       'Callback','baseline_gui  baselinecaculate');
        h = uicontrol ('Style','Push', ...
                       'Units','normalized', ...
                       'Position',[0.845 0.2 0.12 0.06], ...
                       'String','還原預設', ...
                       'FontSize',10, ...
                       'Backgroundcolor',[0.925 0.914 0.847], ...
                       'Callback','baseline_gui dafault');
        h = uicontrol ('Style','Push', ...
                       'Units','normalized', ...
                       'Position',[0.705 0.10 0.12 0.06], ...
                       'String','關於程式', ...
                       'FontSize',10, ...
                       'Backgroundcolor',[0.925 0.914 0.847], ...
                       'Callback','baseline_gui about');
        h = uicontrol ('Style','Push', ...
                       'Units','normalized', ...
                       'Position',[0.845 0.10 0.12 0.06], ...
                       'String','關閉視窗', ...
                       'FontSize',10, ...
                       'Backgroundcolor',[0.925 0.914 0.847], ...
                       'Callback','close(gcf)');

%% 狀態欄       
        % ----------------------------
        % --- 輸出設定選單外框設定 ---
        % ----------------------------
        h = uicontrol ('Style','Edit', ...
                       'Units','normalized', ...
                       'Position',[0.02 0.05 0.66 0.36], ...
                       'BackgroundColor',con,...
                       'HorizontalAlignment','left', ...
                       'FontName','Courier New', ...
                       'FontSize',13, ...
                       'Max',10, ...
                       'Tag','results');
      
        h = uicontrol ('Style','Text', ...
                       'Units','normalized', ...
                       'Position',[0.02 0.41 0.08 0.035], ...
                       'String','執行狀態', ...
                       'FontSize',10, ...
                       'BackgroundColor',[0.9 0.9 0.8]);

%% 互動式介面
        %__________________________________________________________________________________
        % --------------------------------
        % --- 互動式使用者介面 ----
        % --------------------------------
        watchoff(oldFigNumber);
%% baseline calculate
    case 'baselinecaculate' %基線計算
        hout = findobj(gcf,'Tag','results');
        obsfile1 = get(findobj(gcf,'Tag','InputFile1'),'String');
        obsfile2 = get(findobj(gcf,'Tag','InputFile2'),'String');
        navfile  = get(findobj(gcf,'Tag','InputFile3'),'String');
        if any(obsfile1)==0 || any(obsfile2)==0 || any(navfile)==0,
            msg = sprintf([' 請先選擇觀測資料， \n\n', ...
                ' 再進行基線計算。 ']);
            msgbox(msg,' 錯誤訊息','help');
            return
        else
            set(hout,'String',string(1,:));
            inputs.obsfile1 = obsfile1;
            inputs.obsfile2 = obsfile2;
            inputs.navfile = navfile;
        end

        x = str2num(get(findobj(gcf,'Tag','wgsx1'),'String'));
        y = str2num(get(findobj(gcf,'Tag','wgsy1'),'String'));
        z = str2num(get(findobj(gcf,'Tag','wgsz1'),'String'));
        stnxyz(1,:) = [x y z];

        x = str2num(get(findobj(gcf,'Tag','wgsx2'),'String'));
        y = str2num(get(findobj(gcf,'Tag','wgsy2'),'String'));
        z = str2num(get(findobj(gcf,'Tag','wgsz2'),'String'));
        stnxyz(2,:) = [x y z];

        hL1 = findobj(gcf,'Tag','pL1');
        hL2 = findobj(gcf,'Tag','pL2');
        hL5 = findobj(gcf,'Tag','pL5');
        hE1 = findobj(gcf,'Tag','pE1');
        hE5a = findobj(gcf,'Tag','pE5a');
        hE5b = findobj(gcf,'Tag','pE5b');
        obarry = find(cell2mat(get([hL1,hL2,hL5,hE1,hE5a,hE5b],'Value')));
        if any(obarry)==0,
            msg = sprintf([' 請先選擇觀測量， \n\n', ...
                ' 再進行基線計算。 ']);
            msgbox(msg,' 錯誤訊息','help');
            return
        end

        inputs.obstype = obarry;
        inputs.during = get(findobj(gcf,'Tag','coninterval'),'String');
        inputs.multieditor = get(findobj(gcf,'Tag','multi'),'String');
        inputs.ratiocutoff = get(findobj(gcf,'Tag','ratiocut'),'String');
        inputs.outfile = get(findobj(gcf,'Tag','resultout'),'String');
        inputs.slptol = get(findobj(gcf,'Tag','cscutoff'),'String');
        inputs.cutoff = get(findobj(gcf,'Tag','mask'),'String');
        inputs.stnxyz = stnxyz;
        inputs.anth1 = get(findobj(gcf,'Tag','anth1'),'String');
        inputs.anth2 = get(findobj(gcf,'Tag','anth2'),'String');
%         inputs
        set(hout,'String',string(1:2,:));
        GDDAM(inputs);
        set(hout,'String',string);
%% select file
    case 'SelectFile';
        
        switch option;
            case 'In1';    
                [FileName,PathName] = uigetfile ({'*.mat';'*.*O'},'Select file');
                set(findobj(gcf,'Tag','InputFile1'),'String',FileName);
                if any(FileName) == 0, return, end
                in1 = rnxheader(FileName);
                set(findobj(gcf,'Tag','wgsx1'),'String',num2str(in1.STN_XYZ(1)));
                set(findobj(gcf,'Tag','wgsy1'),'String',num2str(in1.STN_XYZ(2)));
                set(findobj(gcf,'Tag','wgsz1'),'String',num2str(in1.STN_XYZ(3)));
                h = findobj(gcf,'Tag','anth1');
                if any(in1.ANT_HEN),
                    set (h,'String',num2str(in1.ANT_HEN(1)));
                else
                    set (h,'String',sprintf('%4.3f',0));
                end
                
                hINP2  = findobj(gcf,'Tag','InputFile2');
                h  = findobj(gcf,'Tag','sO2');
                hx2 = findobj(gcf,'Tag','wgsx2');
                hy2 = findobj(gcf,'Tag','wgsy2');
                hz2 = findobj(gcf,'Tag','wgsz2');
                ha2 = findobj(gcf,'Tag','anth2');
                set([hINP2,h,hx2,hy2,hz2,ha2],'Enable','On');
            case 'In2';
                [FileName,PathName] = uigetfile ({'*.mat';'*.*O'},'Select file');
                if any(FileName) == 0, return, end
                in2 = rnxheader(FileName);
                set(findobj(gcf,'Tag','InputFile2'),'String',FileName);
                set(findobj(gcf,'Tag','wgsx2'),'String',num2str(in2.STN_XYZ(1)));
                set(findobj(gcf,'Tag','wgsy2'),'String',num2str(in2.STN_XYZ(2)));
                set(findobj(gcf,'Tag','wgsz2'),'String',num2str(in2.STN_XYZ(3)));
                h = findobj(gcf,'Tag','anth2');
                if any(in2.ANT_HEN),
                    set(h,'String',num2str(in2.ANT_HEN(1)));
                else
                    set(h,'String',sprintf('%4.3f',0));
                end
                
                hINP3 = findobj(gcf,'Tag','InputFile3');
                h = findobj(gcf,'Tag','sN');
                set([hINP3,h],'Enable','On');
            case 'In3';
                [FileName,PathName] = uigetfile ({'*.mat';'*.*N'},'Select file');
                if any(FileName)==0, return, end
                set(findobj(gcf,'Tag','InputFile3'),'String',FileName);
                
                usetype = chk_obs(in1,in2);                   
                hL1 = findobj(gcf,'Tag','pL1');
                hL2 = findobj(gcf,'Tag','pL2');
                hL5 = findobj(gcf,'Tag','pL5');
                hE1 = findobj(gcf,'Tag','pE1');
                hE5a = findobj(gcf,'Tag','pE5a');
                hE5b = findobj(gcf,'Tag','pE5b');
                set([hL1,hL2,hL5,hE1,hE5a,hE5b],'Value',0);
                if ismember(1,usetype),set(hL1,'Enable','On');else,set(hL1,'Enable','Off');end
                if ismember(2,usetype),set(hL2,'Enable','On');else,set(hL2,'Enable','Off');end
                if ismember(3,usetype),set(hL5,'Enable','On');else,set(hL5,'Enable','Off');end
                if ismember(4,usetype),set(hE1,'Enable','On');else,set(hE1,'Enable','Off');end
                if ismember(5,usetype),set(hE5a,'Enable','On');else,set(hE5a,'Enable','Off');end
                if ismember(6,usetype),set(hE5b,'Enable','On');else,set(hE5b,'Enable','Off');end
                hout = findobj(gcf,'Tag','results');
                set(hout,'String',string{1,:});
        end
%% 
    case 'filename'
        switch option
            case 'stn1'
                FileName = get(findobj(gcf,'Tag','InputFile1'),'String');
                in1 = rnxheader(FileName);
                set (findobj(gcf,'Tag','wgsx1'),'String',num2str(in1.STN_XYZ(1)));
                set (findobj(gcf,'Tag','wgsy1'),'String',num2str(in1.STN_XYZ(2)));
                set (findobj(gcf,'Tag','wgsz1'),'String',num2str(in1.STN_XYZ(3)));
                h = findobj(gcf,'Tag','anth1');
                if any(in1.ANT_HEN),
                    set (h,'String',num2str(in1.ANT_HEN(1)));
                else
                    set (h,'String',sprintf('%4.3f',0));
                end
                
                hINP2  = findobj(gcf,'Tag','InputFile2');
                h  = findobj(gcf,'Tag','sO2');
                hx2 = findobj(gcf,'Tag','wgsx2');
                hy2 = findobj(gcf,'Tag','wgsy2');
                hz2 = findobj(gcf,'Tag','wgsz2');
                ha2 = findobj(gcf,'Tag','anth2');
                set([hINP2,h,hx2,hy2,hz2,ha2],'Enable','On');
            case 'stn2'
                FileName = get(findobj(gcf,'Tag','InputFile2'),'String');
                if any(FileName)==0, return, end
                in2 = rnxheader(FileName);
                set(findobj(gcf,'Tag','InputFile2'),'String',FileName);
                set(findobj(gcf,'Tag','wgsx2'),'String',num2str(in2.STN_XYZ(1)));
                set(findobj(gcf,'Tag','wgsy2'),'String',num2str(in2.STN_XYZ(2)));
                set(findobj(gcf,'Tag','wgsz2'),'String',num2str(in2.STN_XYZ(3)));
                h = findobj(gcf,'Tag','anth2');
                if any(in2.ANT_HEN),
                    set(h,'String',num2str(in2.ANT_HEN(1)));
                else
                    set(h,'String',sprintf('%4.3f',0));
                end
                
                hINP3 = findobj(gcf,'Tag','InputFile3');
                h = findobj(gcf,'Tag','sN');
                set([hINP3,h],'Enable','On');
            case 'eph'
                FileName = get(findobj(gcf,'Tag','InputFile3'),'String');
                if any(FileName)==0, return, end
                
                usetype = chk_obs(in1,in2);                   
                hL1 = findobj(gcf,'Tag','pL1');
                hL2 = findobj(gcf,'Tag','pL2');
                hL5 = findobj(gcf,'Tag','pL5');
                hE1 = findobj(gcf,'Tag','pE1');
                hE5a = findobj(gcf,'Tag','pE5a');
                hE5b = findobj(gcf,'Tag','pE5b');
                set([hL1,hL2,hL5,hE1,hE5a,hE5b],'Value',0);
                if ismember(1,usetype),set(hL1,'Enable','On');else,set(hL1,'Enable','Off');end
                if ismember(2,usetype),set(hL2,'Enable','On');else,set(hL2,'Enable','Off');end
                if ismember(3,usetype),set(hL5,'Enable','On');else,set(hL5,'Enable','Off');end
                if ismember(4,usetype),set(hE1,'Enable','On');else,set(hE1,'Enable','Off');end
                if ismember(5,usetype),set(hE5a,'Enable','On');else,set(hE5a,'Enable','Off');end
                if ismember(6,usetype),set(hE5b,'Enable','On');else,set(hE5b,'Enable','Off');end
                hout = findobj(gcf,'Tag','results');
                set(hout,'String',string{1,:});

        end

%% default
    case 'dafault'
        set(findobj(gcf,'Tag','InputFile1'),'String','');
        set(findobj(gcf,'Tag','wgsx1'),'String','');
        set(findobj(gcf,'Tag','wgsy1'),'String','');
        set(findobj(gcf,'Tag','wgsz1'),'String','');
        set(findobj(gcf,'Tag','anth1'),'String','');
        
        set(findobj(gcf,'Tag','InputFile2'),'String','','Enable','Off');
        set(findobj(gcf,'Tag','wgsx2'),'String','','Enable','Off');
        set(findobj(gcf,'Tag','wgsy2'),'String','','Enable','Off');
        set(findobj(gcf,'Tag','wgsz2'),'String','','Enable','Off');
        set(findobj(gcf,'Tag','anth2'),'String','','Enable','Off');
        set(findobj(gcf,'Tag','sO2'),'Enable','Off');
        
        set(findobj(gcf,'Tag','InputFile3'),'String','','Enable','Off');
        set(findobj(gcf,'Tag','sN'),'Enable','Off');
        
        set(findobj(gcf,'Tag','pL1'),'Value',0,'Enable','Off');
        set(findobj(gcf,'Tag','pL2'),'Value',0,'Enable','Off');
        set(findobj(gcf,'Tag','pL5'),'Value',0,'Enable','Off');
        set(findobj(gcf,'Tag','pE1'),'Value',0,'Enable','Off');
        set(findobj(gcf,'Tag','pE5a'),'Value',0,'Enable','Off');
        set(findobj(gcf,'Tag','pE5b'),'Value',0,'Enable','Off');
        
        set(findobj(gcf,'Tag','multi'),'String','3.0');
        set(findobj(gcf,'Tag','ratiocut'),'String','3');
        set(findobj(gcf,'Tag','coninterval'),'String','15');
        set(findobj(gcf,'Tag','mask'),'String','10');
        set(findobj(gcf,'Tag','cscutoff'),'String','2.5');
        set(findobj(gcf,'Tag','resultout'),'String','result.txt');
        
        set(findobj(gcf,'Tag','results'),'String','');
        
%% About
    case 'about'
        sbar(1:65) = '-';
        sbar2 = blanks(19);
        msg = sprintf([' 提供 GNSS 觀測量之短基線計算 \n',sbar, ...
              '\n 程式版本 : 1.0 \n', ...
              ' 撰  寫  者 : 儲豐宥、張耀允 \n', ...
              ' 電子信箱 : p6894103@mail.ncku.edu.tw \n', ...
              ' 研究單位 : 國立成功大學 測量與空間資訊學系 \n',sbar2, ...
              ' 衛星定位及空間資訊實驗室 \n',sbar, ...
              '\n Release 12-April-2007 ']);
        msgbox(msg,'關於程式','help');

end

       
        
  